### PR TITLE
Remove outdated and extraneous USLCI files

### PR DESCRIPTION
**Pull request by bl-young**
@WesIngwersen Ok to remove these to avoid confusion? The ultimate USLCI mapping file did not rely on these methods.

Also will remove the page on the wiki

### CODE REVIEW

**Comment by bl-young** [comment]
@hottleta can you chime in? I believe these files were from the first iteration of the USLCI mapping before a large number of orphan flows were removed from the database, but did the ultimate mapping build from this list? If so we could keep them and add some more documentation to the top of the script

**Comment by hottleta** [comment]
The mapping file that is currently in use was generated by @WesIngwersen on January 10 using the add_uuid script. This corresponds to the January 9 date for the finalized mapping file (USLCI_updatedmapping_1-9-20_final.csv) which also includes annotations for flows, mapped and unmapped. This mapping file was produced using the same process we have been employing for the other mapping efforts.

I have attached the mapping file here as an xlsx (it wouldn't allow me to upload a csv here).

[USLCI_updatedmapping_1-9-20_final.xlsx](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/files/4267538/USLCI_updatedmapping_1-9-20_final.xlsx)

**Comment by hottleta** [comment]
It looks to me like @bl-young added a cleaned up version of that mapping file without UUIDs, then @WesIngwersen added the UUIDs resulting in the current working version.

**Comment by bl-young** [comment]
Right, so it was essentially a manual mapping that was done by first attempting to map flowables and contexts separately, but all done within Excel. I propose we update the documentation on the wiki to describe that approach specifically for USLCI, instead of maintaining these files which are outdated

**Pull request merged**
