### PR TITLE
Context mapping

### PR DESCRIPTION
**Pull request by bl-young**
-Refactoring for building mapping files to support distinct mappings for flows and contexts
-Add a separate folder for mapping input files to separate from flow list input files
-Mapping for ImpactWorld+ (LCIAfmt: [PR 43](https://github.com/USEPA/LCIAformatter/pull/43))
-Refactor to consolidate code with new functions: add_uuid_to_mapping, add_conversion_to_mapping
-New flows to support USDA_CUS, and addition to this mapping file
-Expanded biological secondary contexts
-New tests for duplicate flows and contexts across classes

Note: changes to some mapping files (NEI, TRI, ReCiPe) primarily reflect reordering following generation by script

### CODE REVIEW

**Review by WesIngwersen — CHANGES_REQUESTED** [review]
the flow mapping unit tests are failing for me 
```
583236 != 583296

Expected :583296
Actual   :583236
<Click to see difference>

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.2.1\plugins\python\helpers\pycharm\teamcity\diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 583296 != 583236

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\wesle\Federal-LCA-Commons-Elementary-Flow-List\tests\test_flow_mappings.py", line 31, in test_no_nas_in_required_fields
    self.assertEqual(len(flowmappings_w_required), len(nas_in_required))



582627 != 583296

Expected :583296
Actual   :582627
<Click to see difference>

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.2.1\plugins\python\helpers\pycharm\teamcity\diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 583296 != 582627

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\wesle\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\wesle\Federal-LCA-Commons-Elementary-Flow-List\tests\test_flow_mappings.py", line 41, in test_targetflowinfo_matches_flows_in_list
    self.assertEqual(len(flowmapping_targetinfo), len(flowmappings_w_flowlist))
```

**Comment by bl-young** [comment]
Yes on the first failure, these flow mappings for USEEIOr don't have source flow contexts. I'll revise them to match the satellite tables.

On the second failure, if you update your parquet it should be resolved. I did not yet push a v1.0.7 parquet but I can on this branch.

**Comment by WesIngwersen** [comment]
FYI in flowlist.py I'm getting this INFO message
```
INFO 145 flows with multiple alt unit; these duplicates have been removed:
         Uranium
         Methane
 Coalbed methane
     Natural gas
```

the flowlist was originally designed only to allow one alternate unit. It will be an enhancement if we allow multiple but they have to be associated with a single flow, so the format of the alt units would likely have to change - perhaps to a list. In the meantime, only one alt unit will be kept

**Comment by WesIngwersen** [comment]
Here is a nice helpful post for dealing with lists in pd dataframes if we go that route
https://towardsdatascience.com/dealing-with-list-values-in-pandas-dataframes-a177e534f173

**Comment by WesIngwersen** [comment]
> Yes on the first failure, these flow mappings for USEEIOr don't have source flow contexts. I'll revise them to match the satellite tables.
> 
> On the second failure, if you update your parquet it should be resolved. I did not yet push a v1.0.7 parquet but I can on this branch.

I confirmed that the second test `test_targetflowinfo_matches_flows_in_list` passes once the list is regenerated. thanks for the tip.

**Comment by bl-young** [comment]
> Here is a nice helpful post for dealing with lists within pd dataframes if we go that route
> https://towardsdatascience.com/dealing-with-list-values-in-pandas-dataframes-a177e534f173

Yes a list might be a better way to go ultimately. Right now the flow list parquet only can handle a single alternate unit. But when the list is generated in JSON the additional alternate units get [re-added](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/blob/master/fedelemflowlist/jsonld.py#L217-L232). That logger line may be better as a debug than an info given the potential confusion it might cause, as flows aren't really getting removed.

**Pull request merged**
