### PR TITLE
Update with use of esupy for flowlist storage

### PR DESCRIPTION
**Pull request by bl-young**
This implements the use of parquet storage via esupy for locally saving the flowlist **and removes the flowlist parquet file from the repository**

Attempting to access the flowlist will cause it to be created if not found locally.

### CODE REVIEW

**Comment by bl-young** [comment]
@WesIngwersen flagging you on this to ensure you are comfortable shifting to local data storage of the flowlist instead of within the repo.

**Comment by WesIngwersen** [comment]
> @WesIngwersen flagging you on this to ensure you are comfortable shifting to local data storage of the flowlist instead of within the repo.

I assume it will store the flowlist parquet on the Data Commons?

**Comment by bl-young** [comment]
I can add the piece to download from data commons (I did not yet since generating locally is quite quick).
Would we prefer that by default users get the flowlist from data commons instead of generating locally?

**Comment by WesIngwersen** [comment]
> I can add the piece to download from data commons (I did not yet since generating locally is quite quick). Would we prefer that by default users get the flowlist from data commons instead of generating locally?

Yes. We should go for consistency across other tools. where the principle API function to get the data in __init__ calls in an esupy function to load from local storage or download it from the Commons if missing.

**Comment by bl-young** [comment]
ok added with c497ab6. I can confirm its working once we have a parquet up there.

**Comment by bl-young** [comment]
Assigning @catherinebirney for preparing data commons upon returning.

**Comment by WesIngwersen** [comment]
tested and works for me

**Pull request merged**
