### PR TITLE
Update to USLCI mapping

### PR DESCRIPTION
**Pull request by ashleyedelen**
update to mis-mapped flow.

Phthalate, dioctyl-
63e7fe64-8549-11e0-9d78-0800200c9a66

in comparing with OpenLCA this same flow was mapped to two different flows. upon further review it was found this flow was mapped incorrectly. This corrects the issue and the flow is not mapped in OpenLCA and USLCI to the same FEDEFL flow.

### CODE REVIEW

**Comment by ashleyedelen** [comment]
Updated TRACI 2.1

TRACI2.1 also had a misidentified chemical with various contexts. The mapping flowable name was corrected along with the UUID

**Comment by bl-young** [comment]
@ashleyedelen the update to TRACI needs to be handled in the TRACIFlowables Mapping file in the inputs folder. Then by running the script we can regenerate the actual mapping file.

**Comment by ashleyedelen** [comment]
@bl-young just checking, this is different than making a correction with the openLCA mapping. There i can just correct the mapping file, correct?

**Comment by ashleyedelen** [comment]
@bl-young so do i need to undo what i did in the mapping file of TRACI2.1?

**Comment by ashleyedelen** [comment]
Corrected the TRACI update, the input TRACI flowable file was corrected. Per @bl-young once running the script this will correct the output file and the mis-matched TRACI flowable will be corrected.

**Review by WesIngwersen — APPROVED** [review]

**Comment by bl-young** [comment]
@ashleyedelen confirming that the TRACI mapping file was updated (note one UUID changed that was missed earlier) here: https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/commit/31e1f3d722589e4826ca53141219f1ed20c6a9b3

**Pull request merged**
