### PR TITLE
Addition of two new flows

### PR DESCRIPTION
**Pull request by bl-young**
for organic carbon and black (elemental) carbon for use with GREET

### CODE REVIEW

**Comment by bl-young** [comment]
Groups makes sense, though I will confirm with Ashley. Both of these are flows associated with PM2.5 typically, if that makes a difference (and would map from the appropriate NEI flows). In this case, black carbon is not the same as carbon black, which is why I did not use the SRS. Black carbon does not appear to be in the SRS.

E.G.: Report on Black Carbon to Congress:
https://yosemite.epa.gov/sab/sabproduct.nsf/f697818d4467059f8525724100810c37/38059D3EA6FE3A19852578EA004A7469/$File/EPA-COUNCIL-11-002-unsigned.pdf

**Comment by WesIngwersen** [comment]
@ashleyedelen @bl-young I do understand that black Carbon is often part of the PM emissions. But its not our role to solve this problem with inventory modeling. The fact is right now that sources like GREET report black Carbon and they also have their own internal LCIA methods that characterize this, and we do want to accommodate that in the FEDEFL. Because it has its own CAS, I recommended it be added to the Chemicals class. 
Total organic carbon can be measured in an air stream. .we might want to follow up with GREET to better understand this flow but if its something measured from an exhaust stream then its probably better places as an Other flow.  Again, I think GREET has its own LCIA methods that characterize it, so I think we need to retain it...but you can follow up with them on that.

**Comment by ashleyedelen** [comment]
The SRS also contains Organic carbon, PM2.5 (https://ofmpub.epa.gov/sor_internet/registry/substreg/searchandretrieve/substancesearch/search.do?details=displayDetails&selectedSubstanceId=78474) and Organic Carbon, PM10 (https://ofmpub.epa.gov/sor_internet/registry/substreg/searchandretrieve/substancesearch/search.do?details=displayDetails&selectedSubstanceId=78473) or Organic Carbon (https://ofmpub.epa.gov/sor_internet/registry/substreg/searchandretrieve/substancesearch/search.do?details=displayDetails&selectedSubstanceId=35872) which is defined as total organic carbon and mentions many different forms of organic carbon, so we could add one or more of these terms along with the carbon black to capture this information.

**Comment by WesIngwersen** [comment]
@ashleyedelen @bl-young Please proceed with this adding those terms to the appropriate class

**Comment by bl-young** [comment]
@WesIngwersen Ok I've made the requested updates and committed.

**Pull request merged**
